-- -- local status, n = pcall(require, 'neosolarized')
-- -- if (not status) then return end
-- --
-- -- n.setup({ comment_italics = true })
-- --
-- -- local colorbuddy = require('colorbuddy.init')
-- local Color, colors, Group, groups, styles = require('colorbuddy').setup()
-- -- local Color = colorbuddy.Color
-- -- local colors = colorbuddy.colors
-- -- local Group = colorbuddy.Group
-- -- local groups = colorbuddy.groups
-- -- local styles = colorbuddy.styles
--
-- Color.new('black', '#000000')
-- -- Color.new('orange', '#7aa2f7')
-- -- Color.new('tokyonight', "#9d7cd8")
-- -- Color.new('blue0', "#3d59a1")
-- -- Color.new('blue', "#7aa2f7")
--
-- Group.new('cursorline', colors.none, colors.base03, styles.NONE, colors.base1)
-- Group.new('CursorLineNr', colors.yellow, colors.black, styles.NONE, colors.base1)
-- Group.new('Visual', colors.none, colors.base03, styles.reverse)
-- -- Group.new('Function', colors.blue, colors.none, styles.bold + styles.italic)
--
-- -- Group.new('Function', colors.yellow, colors.background, styles.bold)
-- -- TODO
-- -- Group.new('TODO', colors.orange, colors.base03, styles.underline + styles.bold)
--
-- local cError = groups.Error.fg
-- local cInfo = groups.Information.fg
-- local cWarn = groups.Warning.fg
-- local cHint = groups.Hint.fg
--
-- Group.new("DiagnosticVirtualTextError", cError, cError:dark():dark():dark():dark(), styles.NONE)
-- Group.new("DiagnosticVirtualTextInfo", cInfo, cInfo:dark():dark():dark(), styles.NONE)
-- Group.new("DiagnosticVirtualTextWarn", cWarn, cWarn:dark():dark():dark(), styles.NONE)
-- Group.new("DiagnosticVirtualTextHint", cHint, cHint:dark():dark():dark(), styles.NOne)
-- Group.new("DiagnosticUnderlineError", colors.none, colors.none, styles.undercurl, cError)
-- Group.new("DiagnosticUnderlineWarn", colors.none, colors.none, styles.undercurl, cWarn)
-- Group.new("DiagnosticUnderlineInfo", colors.none, colors.none, styles.undercurl, cInfo)
-- Group.new("DiagnosticUnderlineHint", colors.none, colors.none, styles.undercurl, cHint)
