return {
  {
    "smjonas/inc-rename.nvim",
    cmd = "IncRename",
    config = true,
  },
  -- {
  --   "hrsh7th/nvim-cmp",
  --   version = false, -- last release is way too old
  --   event = "InsertEnter",
  --   dependencies = {
  --     "neovim/nvim-lspconfig",
  --     "hrsh7th/cmp-nvim-lsp",
  --     "hrsh7th/cmp-buffer",
  --     "hrsh7th/cmp-path",
  --     "hrsh7th/cmp-cmdline",
  --     "hrsh7th/nvim-cmp",
  --     "L3MON4D3/LuaSnip",
  --     "saadparwaiz1/cmp_luasnip",
  --   },
  --   -- Not all LSP servers add brackets when completing a function.
  --   -- To better deal with this, LazyVim adds a custom option to cmp,
  --   -- that you can configure. For example:
  --   --
  --   -- ```lua
  --   -- opts = {
  --   --   auto_brackets = { "python" }
  --   -- }
  --   -- ```
  --
  --   opts = function()
  --     vim.api.nvim_set_hl(0, "CmpGhostText", { link = "Comment", default = true })
  --     local cmp = require("cmp")
  --     local defaults = require("cmp.config.default")()
  --     -- Set configuration for specific filetype.
  --     cmp.setup.filetype("gitcommit", {
  --       sources = cmp.config.sources({
  --         { name = "git" }, -- You can specify the `git` source if [you were installed it](https://github.com/petertriho/cmp-git).
  --       }, {
  --         { name = "buffer" },
  --       }),
  --     })
  --     -- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
  --     cmp.setup.cmdline({ "/", "?" }, {
  --       mapping = cmp.mapping.preset.cmdline(),
  --       sources = {
  --         { name = "buffer" },
  --       },
  --     })
  --     -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  --     cmp.setup.cmdline(":", {
  --       mapping = cmp.mapping.preset.cmdline(),
  --       sources = cmp.config.sources({
  --         { name = "path" },
  --       }, {
  --         { name = "cmdline" },
  --       }),
  --       matching = {
  --         disallow_symbol_nonprefix_matching = false,
  --         disallow_fuzzy_matching = false,
  --         disallow_fullfuzzy_matching = false,
  --         disallow_partial_fuzzy_matching = false,
  --         disallow_partial_matching = false,
  --         disallow_prefix_unmatching = false,
  --       },
  --     })
  --     -- Set up lspconfig.
  --     local capabilities = require("cmp_nvim_lsp").default_capabilities()
  --     require("lspconfig")["tsserver"].setup({
  --       capabilities = capabilities,
  --     })
  --
  --     vim.api.nvim_set_hl(0, "CmpNormal", { bg = "#000000" })
  --     -- set background float completion
  --     return {
  --       snippet = {
  --         -- REQUIRED - you must specify a snippet engine
  --         expand = function(args)
  --           -- vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
  --           require("luasnip").lsp_expand(args.body) -- For `luasnip` users.
  --           -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
  --           -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
  --           vim.snippet.expand(args.body) -- For native neovim snippets (Neovim v0.10+)
  --         end,
  --       },
  --       window = {
  --         -- completion = cmp.config.window.bordered(),
  --         -- documentation = cmp.config.window.bordered(),
  --         completion = {
  --           border = "rounded",
  --           winhighlight = "Normal:CmpNormal",
  --         },
  --         documentation = {
  --           border = "rounded",
  --           winhighlight = "Normal:CmpDocNormal",
  --         },
  --       },
  --       auto_brackets = {}, -- configure any filetype to auto add brackets
  --       completion = {
  --         completeopt = "menu,menuone,noinsert",
  --       },
  --       mapping = cmp.mapping.preset.insert({
  --         ["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
  --         ["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
  --         ["<C-b>"] = cmp.mapping.scroll_docs(-4),
  --         ["<C-f>"] = cmp.mapping.scroll_docs(4),
  --         ["<C-Space>"] = cmp.mapping.complete(),
  --         ["<C-e>"] = cmp.mapping.abort(),
  --         ["<CR>"] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  --         ["<S-CR>"] = cmp.mapping.confirm({
  --           behavior = cmp.ConfirmBehavior.Replace,
  --           select = true,
  --         }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  --         ["<C-CR>"] = function(fallback)
  --           cmp.abort()
  --           fallback()
  --         end,
  --       }),
  --       sources = cmp.config.sources({
  --         { name = "nvim_lsp" },
  --         { name = "path" },
  --         { name = "luasnip" }, -- For luasnip users.
  --         -- { name = "vsnip" }, -- For vsnip users.
  --         -- { name = 'ultisnips' }, -- For ultisnips users.
  --         -- { name = 'snippy' }, -- For snippy users.
  --       }, {
  --         { name = "buffer" },
  --       }),
  --       formatting = {
  --         format = function(_, item)
  --           local icons = require("lazyvim.config").icons.kinds
  --           if icons[item.kind] then
  --             item.kind = icons[item.kind] .. item.kind
  --           end
  --           return item
  --         end,
  --       },
  --       experimental = {
  --         ghost_text = {
  --           hl_group = "CmpGhostText",
  --         },
  --       },
  --       sorting = defaults.sorting,
  --     }
  --   end,
  --   ---@param opts cmp.ConfigSchema | {auto_brackets?: string[]}
  --   config = function(_, opts)
  --     for _, source in ipairs(opts.sources) do
  --       source.group_index = source.group_index or 1
  --     end
  --     local cmp = require("cmp")
  --     local Kind = cmp.lsp.CompletionItemKind
  --     cmp.setup(opts)
  --     cmp.event:on("confirm_done", function(event)
  --       if not vim.tbl_contains(opts.auto_brackets or {}, vim.bo.filetype) then
  --         return
  --       end
  --       local entry = event.entry
  --       local item = entry:get_completion_item()
  --       if vim.tbl_contains({ Kind.Function, Kind.Method }, item.kind) then
  --         local keys = vim.api.nvim_replace_termcodes("()<left>", false, false, true)
  --         vim.api.nvim_feedkeys(keys, "i", true)
  --       end
  --     end)
  --   end,
  -- },
}
